### ISSUE TITLE
is_git function fails grouping None result

### ISSUE THREAD

**Issue by simotrone** [django-daiquiri/dq-dev#7]
The call:
```
Traceback (most recent call last):
  File "manage.py", line 110, in <module>
    dco.render_dc_yaml(conf['args']['run'])
  File "xyz/dq-dev/py/dcompose.py", line 371, in render_dc_yaml
    self.make_volumes()
  File "xyz/dq-dev/py/dcompose.py", line 243, in make_volumes
    if self.valid_volume(v) is True:
  File "xyz/dq-dev/py/dcompose.py", line 309, in valid_volume
    ig = is_git(dev)
  File "xyz/dq-dev/py/util.py", line 89, in is_git
    out = re.search(r'git.*?\s', out).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

The line https://github.com/django-daiquiri/dq-dev/blob/eff9ecd08773b1740e4e56bb9c68863245de6eb2/py/util.py#L89 

assumes that something is found to then do `.group(0)`, but it is not guaranteed.
In fact, a valid git repository can also have a name that does not contain the string "git" in the name.

However, the issue is that if `re.search` does not find any matches, it returns a `None` value on which it is impossible to do `.group(0)` and this breaks the process.

I would suggest to handle the cases in which the string is not what is expected - either by separating the call to `.group`, or with a `try` catching the exception.

**Comment by triole** [comment]
Thanks for the report. Building this check I assumed that the repo was cloned from github using the standard urls. For both of them http and ssh a `git` string will be found inside the remote url. Theoretically a remote url without containing git is thinkable but as I see it quite unusual.

Nonetheless you are right that we should catch the exception. On the other hand it would be reasonable to remove the check for a git string because if git remote does not fail we could assume that it is valid git repository. But for now I'll catch the exception.

https://github.com/django-daiquiri/dq-dev/commit/e4a5e0550a62bf28269d1de2688ccc4e0e68e77c

**Comment by triole** [comment]
The issue is was solved. I close the ticket.
